//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyFree_NET.VerifyFreeWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://verifyFreeWS.streetmaster/", ConfigurationName="VerifyFreeWS.VerifyFree")]
    public interface VerifyFree {
        
        // CODEGEN: Il parametro 'TotOutFree' richiede informazioni sullo schema aggiuntive che non possono essere acquisite utilizzando la modalità parametro. L'attributo specifico è 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://verifyFreeWS.streetmaster/VerifyFree/VerifyFreeRequest", ReplyAction="http://verifyFreeWS.streetmaster/VerifyFree/VerifyFreeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="TotOutFree")]
        VerifyFree_NET.VerifyFreeWS.VerifyFreeResponse VerifyFree(VerifyFree_NET.VerifyFreeWS.VerifyFreeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://verifyFreeWS.streetmaster/VerifyFree/VerifyFreeRequest", ReplyAction="http://verifyFreeWS.streetmaster/VerifyFree/VerifyFreeResponse")]
        System.Threading.Tasks.Task<VerifyFree_NET.VerifyFreeWS.VerifyFreeResponse> VerifyFreeAsync(VerifyFree_NET.VerifyFreeWS.VerifyFreeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://verifyFreeWS.streetmaster/")]
    public partial class inputVerifyFree : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string capField;
        
        private string localitaField;
        
        private string localita2Field;
        
        private string provinciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cap {
            get {
                return this.capField;
            }
            set {
                this.capField = value;
                this.RaisePropertyChanged("cap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string localita {
            get {
                return this.localitaField;
            }
            set {
                this.localitaField = value;
                this.RaisePropertyChanged("localita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string localita2 {
            get {
                return this.localita2Field;
            }
            set {
                this.localita2Field = value;
                this.RaisePropertyChanged("localita2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string provincia {
            get {
                return this.provinciaField;
            }
            set {
                this.provinciaField = value;
                this.RaisePropertyChanged("provincia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://verifyFreeWS.streetmaster/")]
    public partial class outVerifyFree : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string capField;
        
        private int codComuneField;
        
        private string comuneField;
        
        private string frazioneField;
        
        private string provEstesaField;
        
        private string provinciaField;
        
        private string regioneField;
        
        private int scoreComuneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cap {
            get {
                return this.capField;
            }
            set {
                this.capField = value;
                this.RaisePropertyChanged("cap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codComune {
            get {
                return this.codComuneField;
            }
            set {
                this.codComuneField = value;
                this.RaisePropertyChanged("codComune");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string comune {
            get {
                return this.comuneField;
            }
            set {
                this.comuneField = value;
                this.RaisePropertyChanged("comune");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string frazione {
            get {
                return this.frazioneField;
            }
            set {
                this.frazioneField = value;
                this.RaisePropertyChanged("frazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string provEstesa {
            get {
                return this.provEstesaField;
            }
            set {
                this.provEstesaField = value;
                this.RaisePropertyChanged("provEstesa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string provincia {
            get {
                return this.provinciaField;
            }
            set {
                this.provinciaField = value;
                this.RaisePropertyChanged("provincia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string regione {
            get {
                return this.regioneField;
            }
            set {
                this.regioneField = value;
                this.RaisePropertyChanged("regione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int scoreComune {
            get {
                return this.scoreComuneField;
            }
            set {
                this.scoreComuneField = value;
                this.RaisePropertyChanged("scoreComune");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://verifyFreeWS.streetmaster/")]
    public partial class totOutFree : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codErrField;
        
        private int normField;
        
        private int numCandField;
        
        private outVerifyFree[] outItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codErr {
            get {
                return this.codErrField;
            }
            set {
                this.codErrField = value;
                this.RaisePropertyChanged("codErr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int norm {
            get {
                return this.normField;
            }
            set {
                this.normField = value;
                this.RaisePropertyChanged("norm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int numCand {
            get {
                return this.numCandField;
            }
            set {
                this.numCandField = value;
                this.RaisePropertyChanged("numCand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("outItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public outVerifyFree[] outItem {
            get {
                return this.outItemField;
            }
            set {
                this.outItemField = value;
                this.RaisePropertyChanged("outItem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifyFree", WrapperNamespace="http://verifyFreeWS.streetmaster/", IsWrapped=true)]
    public partial class VerifyFreeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://verifyFreeWS.streetmaster/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VerifyFree_NET.VerifyFreeWS.inputVerifyFree inFree;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://verifyFreeWS.streetmaster/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key;
        
        public VerifyFreeRequest() {
        }
        
        public VerifyFreeRequest(VerifyFree_NET.VerifyFreeWS.inputVerifyFree inFree, string key) {
            this.inFree = inFree;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifyFreeResponse", WrapperNamespace="http://verifyFreeWS.streetmaster/", IsWrapped=true)]
    public partial class VerifyFreeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://verifyFreeWS.streetmaster/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VerifyFree_NET.VerifyFreeWS.totOutFree TotOutFree;
        
        public VerifyFreeResponse() {
        }
        
        public VerifyFreeResponse(VerifyFree_NET.VerifyFreeWS.totOutFree TotOutFree) {
            this.TotOutFree = TotOutFree;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VerifyFreeChannel : VerifyFree_NET.VerifyFreeWS.VerifyFree, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VerifyFreeClient : System.ServiceModel.ClientBase<VerifyFree_NET.VerifyFreeWS.VerifyFree>, VerifyFree_NET.VerifyFreeWS.VerifyFree {
        
        public VerifyFreeClient() {
        }
        
        public VerifyFreeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VerifyFreeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VerifyFreeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VerifyFreeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VerifyFree_NET.VerifyFreeWS.VerifyFreeResponse VerifyFree_NET.VerifyFreeWS.VerifyFree.VerifyFree(VerifyFree_NET.VerifyFreeWS.VerifyFreeRequest request) {
            return base.Channel.VerifyFree(request);
        }
        
        public VerifyFree_NET.VerifyFreeWS.totOutFree VerifyFree(VerifyFree_NET.VerifyFreeWS.inputVerifyFree inFree, string key) {
            VerifyFree_NET.VerifyFreeWS.VerifyFreeRequest inValue = new VerifyFree_NET.VerifyFreeWS.VerifyFreeRequest();
            inValue.inFree = inFree;
            inValue.key = key;
            VerifyFree_NET.VerifyFreeWS.VerifyFreeResponse retVal = ((VerifyFree_NET.VerifyFreeWS.VerifyFree)(this)).VerifyFree(inValue);
            return retVal.TotOutFree;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VerifyFree_NET.VerifyFreeWS.VerifyFreeResponse> VerifyFree_NET.VerifyFreeWS.VerifyFree.VerifyFreeAsync(VerifyFree_NET.VerifyFreeWS.VerifyFreeRequest request) {
            return base.Channel.VerifyFreeAsync(request);
        }
        
        public System.Threading.Tasks.Task<VerifyFree_NET.VerifyFreeWS.VerifyFreeResponse> VerifyFreeAsync(VerifyFree_NET.VerifyFreeWS.inputVerifyFree inFree, string key) {
            VerifyFree_NET.VerifyFreeWS.VerifyFreeRequest inValue = new VerifyFree_NET.VerifyFreeWS.VerifyFreeRequest();
            inValue.inFree = inFree;
            inValue.key = key;
            return ((VerifyFree_NET.VerifyFreeWS.VerifyFree)(this)).VerifyFreeAsync(inValue);
        }
    }
}
